<?php
return [
    [
        'menu_name' => '快递系统',
        'menu_key' => 'fcapi_web_site',
        'menu_short_name' => '快递',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => 'iconfont iconyingyongshichang',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => '',
        'sort' => '110',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '订单管理',
                'menu_key' => 'fcapi_order_add_order_orderAdd',
                'menu_short_name' => '订单',
                'menu_type' => '0',
                'icon' => 'nc-iconfont nc-icon-liebiaoV6xx',
                'api_url' => '',
                'router_path' => '',
                'view_path' => '',
                'methods' => '',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '日志列表',
                        'menu_key' => 'fcapi_order_log_order_orderLog_list',
                        'menu_short_name' => '日志列表',
                        'menu_type' => '1',
                        'icon' => 'iconfont-iconwodedingdan',
                        'api_url' => 'fcapi/orderlog/get/get',
                        'router_path' => 'fcapi/order/orderlog',
                        'view_path' => 'order/orderlog',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '订单列表',
                        'menu_key' => 'fcapi_order_order_order_list',
                        'menu_short_name' => '订单列表',
                        'menu_type' => '1',
                        'icon' => 'iconfont-iconwodedingdan',
                        'api_url' => 'fcapi/order/get/get',
                        'router_path' => 'fcapi/order/order',
                        'view_path' => 'order/order',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '补差订单',
                        'menu_key' => 'fcapi_order_add_order_orderAdd_list',
                        'menu_short_name' => '补差订单',
                        'menu_type' => '1',
                        'icon' => 'iconfont-iconwodedingdan',
                        'api_url' => 'fcapi/orderadd/get',
                        'router_path' => 'fcapi/order/orderadd',
                        'view_path' => 'order/orderadd',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '订单日志添加',
                        'menu_key' => 'fcapi_order_log_order_orderLog_add',
                        'menu_short_name' => '订单日志添加',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'fcapi/orderlog/post',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '订单列添加',
                        'menu_key' => 'fcapi_order_order_order_add',
                        'menu_short_name' => '订单列添加',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'fcapi/order/post/post',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '订单列添加',
                        'menu_key' => 'fcapi_order_add_order_orderAdd_add',
                        'menu_short_name' => '订单列添加',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'fcapi/orderadd',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '订单列编辑',
                        'menu_key' => 'fcapi_order_add_order_orderAdd_edit',
                        'menu_short_name' => '订单列编辑',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'fcapi/orderadd/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '订单日志编辑',
                        'menu_key' => 'fcapi_order_log_order_orderLog_edit',
                        'menu_short_name' => '订单日志编辑',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'fcapi/orderlog/<id>/put',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '订单列编辑',
                        'menu_key' => 'fcapi_order_order_order_edit',
                        'menu_short_name' => '订单列编辑',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'fcapi/order/<id>/put/put',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '订单列删除',
                        'menu_key' => 'fcapi_order_order_order_delete',
                        'menu_short_name' => '订单列删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'fcapi/order/<id>/delete/delete',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '订单列删除',
                        'menu_key' => 'fcapi_order_add_order_orderAdd_delete',
                        'menu_short_name' => '订单列删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'fcapi/orderadd/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '订单日志删除',
                        'menu_key' => 'fcapi_order_log_order_orderLog_delete',
                        'menu_short_name' => '订单日志删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'fcapi/orderlog/<id>/delete',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '站点余额',
                'menu_key' => 'site_app_balance',
                'menu_short_name' => '站点余额',
                'menu_type' => '1',
                'icon' => 'element Money',
                'api_url' => 'fcapi/site/balance',
                'router_path' => 'fcapi/site/balance',
                'view_path' => 'app/balance/index',
                'methods' => 'get',
                'sort' => '0',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => 'API接口',
                'menu_key' => 'site_app_api',
                'menu_short_name' => 'API',
                'menu_type' => '1',
                'icon' => 'element Money',
                'api_url' => 'fcapi/api/manage',
                'router_path' => 'fcapi/api/manage',
                'view_path' => 'app/api/index',
                'methods' => 'get',
                'sort' => '0',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '沙盒测试',
                'menu_key' => 'app_api_sandbox',
                'menu_short_name' => '沙盒测试',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'fcapi/api/sandbox/<id>',
                'router_path' => 'fcapi/api/sandbox',
                'view_path' => 'app/api/sandbox',
                'methods' => 'get',
                'sort' => '0',
                'status' => '1',
                'is_show' => '0',
            ],
        ],
    ],
];